config/routes.rb
Rails.application.routes.draw do
  




  get 'contacts/index'
  get 'contacts/create'
  #brunk routes
  get 'brunks/step1/:id' , to: 'brunks#step1', as: 'step1'
  get 'brunks/step2/:id1/:id2' , to: 'brunks#step2', as: 'step2'
  get 'brunks/my_brunks', to: 'brunks#my_brunks', as: 'my_brunks'
  get 'brunks/show/:id', to: 'brunks#show', as: 'show'
  get 'brunks/show_required/:id', to: 'brunks#show_required', as: 'show_required'
  get 'brunks/brunks_required', to: 'brunks#brunks_required', as: 'brunks_required'

  post 'brunks/create_brunk', to: 'brunks#create_brunk', as: 'create_brunk'

  #
  resources :properties
  resources :countries
  devise_for :runners , :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  
  get "runner_home", to: "welcome#runner_home", as: "runner_home"
  
  get "pagina_show", to: "welcome#pagina_show", as: "pagina_show"
  
  get "runners_avatar", to: "welcome#runners_avatar", as: "runners_avatar"

  get "index_contacs", to: "welcome#index_contacs", as: "index_contacs"

  post "cambios/:id", to: "properties#cambios", as: "cambios"

  #contacto routes

  post "new_contact", to: "contacts#create", as: "new_contact"
  get 'properties/:id' , to: 'properties#show', as: 'properties_show'

  
  get 'crear_call/:id' , to: 'contacts#crear_call', as: 'crear_call'  
  post "new_comment_brunk", to: "brunks#new_comment_brunk", as: "new_comment_brunk"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :authenticate_runner!, :except => [:index, :runners_avatar] 


	def index


	end	

	def runners_avatar
		if params[:search] || params[:search1] || params[:search2] || params[:search3]
			@runner = Runner.all.search(params[:search], params[:search1],params[:search2],params[:search3]).paginate(:page => params[:page], :per_page => 4)
		else
			@runner = Runner.all.paginate(:page => params[:page], :per_page => 4)
		end
		
	end

	def runner_home
		@properties = Property.where(runner_id: current_runner.id).paginate(:page => params[:page], :per_page => 4)
		render :layout => "runner_home"
	end

	def pagina_show
		@properties =  Property.where(runner_id: current_runner.id).show_true.paginate(:page => params[:page], :per_page => 4)
		render :layout => "runner_home"
		
	end

	def index_contacs
		@contact = Contact.all.paginate(:page => params[:page], :per_page => 4)
		render :layout => "runner_home"
	end


end

app/views/welcome/_buscador.html.erb
<div class="container-fluid" id="buscador">

	<%= form_tag properties_path, :method => 'get' do%>

        <div class="col-md-3" style="margin-left: 10%;">
          <%= select_tag 'search2', options_for_select(get_country.collect{ |u| ["#{u.name}", u.id, ] }),{:class => "form-control sh4", include_blank: true, :prompt => 'Seleciona Un Pais' }%>
        </div>

        <div class="col-md-3">
          <%= text_field_tag :search,params[:search], autocomplete: "off", :requerid => true, placeholder: "Buscar Por Ciudad", class: "form form-control"%>
        </div>

        <div class="col-md-3">

          <%= select_tag 'search3', options_for_select(["Apartamento", "Casa", "Finca", "Parqueadero","Oficina", "Local", "Bodega", "Lote","Habitacion", "Consultorio", "Edificio", "Cabaña","Casa Campestre", "Aparta Estudio", "Casa Lote"]),{:class => 'form form-control select' , :prompt => 'Tipo de Inmueble'}%>
        </div>


        <div class="col-md-2" style=" padding: 0px; width: 99px;">

          <%= button_tag class: "btn btn-primary sh3", :title => "Buscar Registros", id: "btn3" do %>
          <i class="fas fa-search" style=""></i> Buscar
          <% end -%>

        </div>

      <% end -%>

</div>

app/views/welcome/_filtros.html.erb
<div class="container-fluid" id="filtros">

  <h4><%= @runner.count %> Runners Disponibles <br></h4> <i><%= page_entries_runner @runner %></i><br><br>

        <%= form_tag runners_avatar_path, :method => 'get' do%>

        <div class="col-md-2" style="float: right; padding: 0px; width: 99px;">
          <%= link_to runners_avatar_path, :title => "Cancelar Filtros", class: "btn btn-danger", id: "btn3" do%>
            <i class="fas fa-ban"></i>
          <% end -%> 

          <%= button_tag class: "btn btn-primary sh3", :title => "Buscar Registros", id: "btn3" do %>
          <i class="fas fa-search" style=""></i>
          <% end -%>

        </div>

        <div class="col-md-3" style="padding-left: 2px; padding-right: 2px;">
          <%= text_field_tag :search,params[:search], autocomplete: "off", :requerid => true, placeholder: "Buscar Por Nombre", class: "form form-control"%>
        </div>

        <div class="col-md-3" style=" padding-right: 2px; padding-left: 2px;">
          <%= email_field_tag :search1,params[:search1], autocomplete: "off", :requerid => true, placeholder: "Buscar Por Email", class: "form form-control"%>
        </div>

        <div class="col-md-3" style=" padding-right: 2px;  padding-left: 2px;">
          <%= text_field_tag :search2,params[:search2], autocomplete: "off", :requerid => true, placeholder: "Buscar Por Ciudad", class: "form form-control"%>
        </div>

        <div class="col-md-1" style=" padding-right: 2px; padding-left: 2px;">
        <%= select_tag 'search3', options_for_select(get_country.collect{ |u| ["#{u.name}", u.id, ] }),{:class => "form-control sh4", include_blank: true, :prompt => 'Seleciona Un Pais', style: "width: 181px !important;" }%>
        </div>

      <% end -%>
</div>


<style>

  #filtros{
    background: #efecec;
    width: 100%;
    padding: 10px;
    margin-left: 1px;
    margin-right: 1px;
  }

  #count{
    background: #0d67c3;
    padding: 5px 11px;
    border-radius: 2px;
    margin-left: 10px;
    margin-right: 10px;
  }

  #btn3{
    float: right;
    margin-left: 10px;
  }

  #filtros h4{
    color: #696a73;
    text-transform: capitalize;
  }

</style>

app/views/welcome/_property.html.erb
 <div class="card">
                    <div class="card-body">
                        <div class="row" style="padding: 9px;">

                            <div class="col-md-3" style="padding-bottom:20px;">
                                
                                <%= property.images? ? image_tag(property.images_url(:medium)) : image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiS5HhpjhUIciPRhbw4Qe_9ms0umoNaHNRltq8qZD13yyRDY6wyQ") %>

                            </div>

                            <div class="col-md-9 info" style="">

                               <div class="col-md-12">
                                <p style="margin-left: 5px;margin-bottom: 10px;" > <strong><%= property.property_type%> - <%= property.city%> - <%=property.country.name if property.country%></strong>
                                   <%= link_to 'Brunk', step1_path(property.id), class: "btn2", style: "float:right;margin-left:10px;" if action_name == "pagina_show"%>
                                <%= link_to 'Ver Propiedad', property, class: "btn2", style: "float:right"%>

                                </p>
                                <small > <strong> Area: </strong><%= property.area%>,00 m2</small>
                              <small><strong> Habitaciones: </strong><%= property.number_bedrooms%> hab</small>
                              <small><strong> Estrato: </strong> <%= property.stratum%></small>
                              </div>
                            

                          

                              <div class="col-md-12">
                                <hr>
                                    <div class="row" style="padding-left: 10px;">
                                      
                                  <div class="col-md-4" style="padding-top: 10px">
                                      <%= link_to  edit_property_path(property) do%>
                        <i class="fas fa-pencil-alt" style = "font-size:20px;margin-right: 10px" aria-hidden="true"></i>
                    <% end -%>
                                  <%= link_to  property, method: :delete, data: {
                                       confirm: '¿Estas Seguro?',
                                       'confirm-button-text': 'Borrar',
                                       'cancel-button-text': 'Cancelar',
                                       'confirm-button-color': '#CC0000',
                                        text: 'Recuerda que el registro se borrara permanentemente',
                                       'image-url': ''} do%>
                                    <i class="fas fa-trash-alt" style = "font-size:20px;" aria-hidden="true"></i>
                                <% end -%>  
                                </div>
                                       <div class="col-md-8" style="    padding-right: 27px; font-size: 20px;text-align: right;">
                                   
                                        <small><b>Precio: </b><%= number_to_currency(property.prince, precision: 0) %></small>
                                      </div>
                                  
                            </div>
                         </div>
                   </div>
          </div>                            
     </div>
</div>

<style>
hr
{
    margin-top: 5px;
    margin-bottom: 5px;
}
.alert-success, .alert-danger
{
  font-size: 20px;
  padding: 5px;
  text-align: center;
}
  img{
    width: 140px !important;
    height: 80px; 

  }
  .info small
  {
   
    padding: 4px;
    margin-right: 10px;
  }
 
</style>

app/views/welcome/_runner_items.html.erb
<div class="card">
  <div class="card-body">
    <div class="row" style="padding: 9px;">
      <div class="col-md-3 image-profile" style="padding-bottom:20px;">
                                
        <%= runner.image? ? image_tag(runner.image_url(:logo)) : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg")%>
      </div>

      <div class="col-md-9 info">
        <div class="col-md-12">
          <b>Nombre: </b><%= runner.name%><br><br>
          <b>Email: </b><%= runner.email %><br><br>
          <b>Numero de Propiedade: </b><%= Property.where(runner_id: runner.id).count %>  

          <div class="col-md-3" style="float: right; padding: 0px;">
            <p><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i></p>
          </div>

        </div>
                          
      </div>
    </div>                            
  </div>
</div>

<style>
  .image-profile img{
    border-radius: 50%;
    height: 150px;
  }

  .fa-star{
    color: #fbe916;
  }
 
</style>

app/views/welcome/index.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<div class="container">
	<div class="row"><br>
			<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="width: 100%;">
			  <ol class="carousel-indicators" style=" margin-left: auto; margin-right: auto;">
			    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
			    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
			    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
			  </ol>
			  <div class="carousel-inner">
			  	<!--
			    <div class="carousel-item active">

			      <img class="d-block w-100" src="https://banknxt.com/wp-content/uploads/2016/09/In-an-ultra-connected-world-what-is-a-bank-810x405.jpg" alt="First slide">
			      <div class="carousel-caption d-none d-md-block">
				    <h1 style="    font-size: 40px;    background: rgba(0, 0, 0, 0.61);">CONECTAMOS EL MUNDO</h1>
				    <p></p>
				  </div>
			    </div>
				-->

			    <div class="carousel-item active">
			      <img class="d-block w-100" src="https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/55/Connected-Globe-Header.jpg" alt="Second slide" height="437" style="opacity: 0.9;">
				  <div class="carousel-caption d-none d-md-block">
				    <h1>CONECTAMOS EL MUNDO</h1>
				    <p>Mediante los Runners</p>
				  </div>
			    </div>
			    <!--
			    <div class="carousel-item">
			      <img class="d-block w-100" src="https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/56/travel-2313444_1920.jpg" alt="Third slide">
			      <div class="carousel-caption d-none d-md-block">
				    <h1>MILES DE INMUEBLES AL REDEDOR DEL MUNDO </h1>
				    <p>Mediante los Runners</p>
				  </div>
			    </div>
				-->

			  </div>
			  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
			    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
			    <span class="carousel-control-next-icon" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			  </a>
			</div>
		<%= render "buscador"%>
	</div>


	  <hr>
	  <div class="container-fluid runner-image" style="padding: 0px;">

	  	<div class="col-md-6" style="padding: 0px;">
			  <img src="https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/49/WhatsApp_Image_2018-10-23_at_10.07.52_AM.jpeg" >
            <br>
	  	</div>

	  	<div class="col-md-6" style="padding-right: 0px;">
		  <div class="panel panel-default"><br> 
				<h3 align="center">Que es un Runner?</h3>
			  <div class="panel-body">
			    <ul>

			    	<li>Los runners son aquellos participes de la empresa que tienen la posibilidad de ganar dinero por medio de ventas realizadas por montajes hechos en la plataforma.</li><br>

			    	<li>Por cada venta realizada se genera una ganancia que se refleja en un número de créditos que el runner podrá cambiar por dinero o dejarlos en la plataforma y si acumulan una cantidad de créditos equivalente al valor de un inmueble pueden comprarlo por medio de estos, de esta forma, los runners podrán ver BRUNK como una oportunidad de ganar dinero e invertir. </li>
			    	
			    </ul> 
			    <br>
			  </div>
		  </div>
		</div>
	  </div>
	  
	  <br>
	  	<h2 align="center">NUESTRAS PROPIEDADES ESTAN POR TODO EL MUNDO</h2>
	  <br>
	  <div class="row image-map">
	  	<img src="https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/58/mapa1.png">
	  </div>


	<div class="col-md-7 col-md-offset-3">
		<h1 align="center" style="margin-top: 100px;">¿POR QUÉ EBRUNK ES PARA TI?</h1>
		  <hr>
			<br><br>
	</div>


	  <div class="container-fluid" style="padding: 0px;">
	  	<div class="col-md-6" style="padding-left: 0px;">
		  <div class="panel panel-default"><br>
		  	<h3 align="center">Videos En 3D</h3>
			  <div class="panel-body" style="padding-bottom: 40% !important;">

			    <ul>
			    	<li>Gracias a las tecnologias hoy en dia podemos hacer que tu propiedad se vista por las personas en 3D, dandole mas oportunidad de campo de vision de todas las partes de tu inmueble</li>
			    </ul>

			  </div>
		  </div>
		</div>
	  	<div class="col-md-6" style="padding: 0px;">
	  		<div class="carousel"
			  data-flickity='{ "imagesLoaded": true, "percentPosition": false }'>
			 <iframe width="580" height="400" src="https://my.matterport.com/show/?model=g8ioLttQigi" allowfullscreen allow="vr"></iframe>
			</div>
	  	</div>
	  </div>
        <br>
	  <hr>

	  <div class="container-fluid" style="padding: 0px; margin-top: 40px;">
	  	<div class="col-md-6" style="padding: 0px;">
	  		<div class="carousel"
			  data-flickity='{ "imagesLoaded": true, "percentPosition": false }'>
				<img src="https://www.adslzone.net/app/uploads/2018/05/whatsapp-videollamada.jpg">
			</div>
	  	</div>

	  	<div class="col-md-6" style="padding-left: 0px;">
		  <div class="panel panel-default"><br>
		  	<h3 align="center">Video llamada</h3>
			  <div class="panel-body" style="padding-bottom: 23% !important;">

			    <ul>
			    	<li>No tienes tiempo para visitar la propiedad que deseas? no te preocupes. puedes contactar con el runner que publico el inmueble y el te hara un tour de la casa desde video llama y podras ver cada rincon de la casa en tiempo real </li>
			    </ul>

			  </div>
		  </div>
		</div>
	  </div>
	  <br>
	  <hr>
	  <br><br>

	  <div class="container-fluid" style="padding: 0px;">
	  	<div class="col-md-6" style="padding-left: 0px;">
		  <div class="panel panel-default"><br>
		  	<h3 align="center">Galeria de Images</h3>
			  <div class="panel-body">

			    <ul>
			    	<li>es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien</li><br>

			    	<li>ingresó como texto de relleno en documentos electrónicos, quedando esencia</li>
			    </ul>

			  </div>
		  </div>
		</div>
	  	<div class="col-md-6" style="padding: 0px;">
	  		<div class="carousel imagenes"
			  data-flickity='{ "imagesLoaded": true, "percentPosition": false }'>

			 <img src="https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/50/luxury-home-2412145_1920.jpg">

			 <img src="https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/52/beautiful-home-2826052_1920.jpg">

			 <img src="https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/51/dining-2112653_1920.jpg">

			 <img src="https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/53/large-home-389271_1280.jpg">

			</div>
	  	</div>
	  </div>
	  <br>
	  <hr>
	  <br><br><br>

	</div>
</div>

<style>
    @import url(//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css);
    #carouselExampleIndicators img{
    	height: 437px !important; 
    }	

   hr{

    	display: block;
	    margin-top: 0.5em;
	    margin-bottom: 0.5em;
	    margin-left: auto;
	    margin-right: auto;
	    border-style: inset;
	    border-width: 1px;
	    background: #0fa1e0 !important;
    }

    .imagenes img{
    	 width: 100%;
    }

    .image-map img{
   		margin-left: 82px;

    }

    .runner-image img{
    	height: 300px;
	    width: 69%;
	    margin-top: 28px;
    }


</style>

app/views/welcome/index_contacs.html.erb
<div class="row" style="background: #fff; border-radius: 4px;">
 <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="col-md-12">
      <div class="row mb-3">
         <div class="col-md-10 col-md-offset-1">
            <h1 align="center">Peticion de video llamada</h1><br>
             <% @contact.each do |contacto| %>
                 <div class="card" style="padding: 20px;">
                    <div class="card-body">
                        <div class="row" style="padding: 9px;">
                         <div class="row" style="margin-bottom: 10px;">

                          <div class="col-md-1">
                            <b>Nombre</b><br>
                            <%= contacto.name%>
                          </div>

                          <div class="col-md-6" style="padding-left: 50px;">
                            <b>Email</b><br>
                            <%= contacto.email%>
                          </div>

                          <div class="col-md-2 icon" style="padding-right: 0px;">
                            <b>Llamar <img src="http://icons.iconarchive.com/icons/martz90/circle-addon2/512/google-hangouts-icon.png"></b><br>
                             <%= get_state_call(contacto.state_call) %>
                          </div>

                          <div class="col-md-3" style="padding-left: 0px;">
                            <b>Fecha</b><br>
                            <%= get_date_hora(contacto.datetime_call) %>
                          </div>
                        </div>
                          <div class="col-md-10" style="padding: 0px;">
                            <b>Mensage</b><br>
                            <%= contacto.message%>
                          </div>

                          <div class="col-md-4" style="padding: 0px; float: right;">
                            <%= link_to "Programar Call", crear_call_path(contacto.id), remote: true , class: "btn btn-primary" if contacto.state_call%>
                            <%= link_to "Llamar", contacto.url_call, class: "btn btn-success" if contacto.url_call%>
                          </div>

                        </div>
                    </div>
                </div>
              <% end -%>
              </div>
            <div class="body">
          <div id="real_time_chart" class="dashboard-flot-chart"></div>
        </div>
      </div>
    </div>
</div>
<!--<div class="col-md-offset-1">
    <%= will_paginate @contact, renderer: BootstrapPagination::Rails, previous_label: "Anterior", next_label: "Siguiente", inner_window: 1, outer_window: 0 %>
</div>
-->
</div>

<style type="text/css">
  .icon img{
    width: 20px;
  }
</style>

app/views/welcome/pagina_show.html.erb
<div class="row" style="background: #fff; border-radius: 4px;">
 <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="col-md-12">
      <div class="row mb-3">
         <div class="col-md-10 col-md-offset-1">
            <h1 align="center">Propiedades Para Intercambio </h1><br>
             <% @properties.each do |property| %>
               
                   <%=render 'property' , property: property  %>
                <% end -%>
              </div>
            <div class="body">
          <div id="real_time_chart" class="dashboard-flot-chart"></div>
        </div>
      </div>
    </div>
</div>
<div class="col-md-offset-1">
    <%= will_paginate @properties, renderer: BootstrapPagination::Rails, previous_label: "Anterior", next_label: "Siguiente", inner_window: 1, outer_window: 0 %>
</div>
    </section>
<br><br>

</body>

</html>

app/views/welcome/runner_home.html.erb
<div class="row" style="background: #fff; border-radius: 4px;">
 <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="col-md-12">
      <div class="row mb-3">
         <div class="col-md-10 col-md-offset-1">
          <% if @properties.any? %>
            <h1 align="center">Mis publicaciones</h1><br>
            <% @properties.each do |property| %>
             <%=render 'property' , property: property  %>
          
                <% end -%>
              </div>
            <div class="body">
          <div id="real_time_chart" class="dashboard-flot-chart"></div>
        </div>
      </div>
    </div>
</div>

<% else %>
    <br>
    <div class="jumbotron jumbotron-fluid" id="jumbo">
      <div class="container">
        <h3 class="display-4" align="center">No Tienes Propiedades Creadas</h3><br>
        <p align="center"><%= link_to "Crear Nueva Propiedad", new_property_path, class: "btn2"%></p>
      </div>
    </div>

<% end -%>

<div class="col-md-offset-1">
    <%= will_paginate @properties, renderer: BootstrapPagination::Rails, previous_label: "Anterior", next_label: "Siguiente", inner_window: 1, outer_window: 0 %>
</div>
    </section>
<br><br>

</body>

</html>

app/views/welcome/runners_avatar.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<section class="mb-5">
    <div class="container">
    <div class="row title py-3">
        <div class="col-md-12" style="padding-left: 0px;">
            <%= render "filtros"%>
        </div>
    </div>    
    <div class="row">
        <div class="col-md-3">
          <div class="row mb-3">
              <div class="col-md-12" style="padding: 0px;">
                  <div class="card">
                      <div class="card-body">
                        <%= form_tag properties_path, :method => 'get' do%>
                          <strong><p>Los Runners</p></strong>
                          <ul class="list-unstyled">

                            <li>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la cre</li>
                            
                          </ul>

                        <% end -%>
                      </div>
                  </div>
              </div>
          </div>
        </div>
        <div class="col-md-9">
            <div class="row mb-3">
                <div class="col-md-12">
                  <% @runner.each do |runner| %>  
                    <%= render "runner_items", runner: runner%>
                    <br>
                  <% end -%>
                </div>
                                          <div class = "col-md-12 paginate text-center title-table1">
    <%= will_paginate @runner, renderer: BootstrapPagination::Rails, previous_label: "Anterior", next_label: "Siguiente", inner_window: 1, outer_window: 0 %>
  </div>
            </div>           
        </div>
    </div>
</div>
</section>

<style>

.bg-orange {
  background:#d8622b;color:#fff!important;
}

body{
  background:#f4f4f4;
}

img{
  width:100%;max-height:560px;
}

a{
  color:#696969;
}

.card-body{
  font-size: 18px;
}
</style>