config/routes.rb
Rails.application.routes.draw do
  




  get 'contacts/index'
  get 'contacts/create'
  #brunk routes
  get 'brunks/step1/:id' , to: 'brunks#step1', as: 'step1'
  get 'brunks/step2/:id1/:id2' , to: 'brunks#step2', as: 'step2'
  get 'brunks/my_brunks', to: 'brunks#my_brunks', as: 'my_brunks'
  get 'brunks/show/:id', to: 'brunks#show', as: 'show'
  get 'brunks/show_required/:id', to: 'brunks#show_required', as: 'show_required'
  get 'brunks/brunks_required', to: 'brunks#brunks_required', as: 'brunks_required'

  post 'brunks/create_brunk', to: 'brunks#create_brunk', as: 'create_brunk'

  #
  resources :properties
  resources :countries
  devise_for :runners , :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  
  get "runner_home", to: "welcome#runner_home", as: "runner_home"
  
  get "pagina_show", to: "welcome#pagina_show", as: "pagina_show"
  
  get "runners_avatar", to: "welcome#runners_avatar", as: "runners_avatar"

  get "index_contacs", to: "welcome#index_contacs", as: "index_contacs"

  post "cambios/:id", to: "properties#cambios", as: "cambios"

  #contacto routes

  post "new_contact", to: "contacts#create", as: "new_contact"
  get 'properties/:id' , to: 'properties#show', as: 'properties_show'

  
  get 'crear_call/:id' , to: 'contacts#crear_call', as: 'crear_call'  
  post "new_comment_brunk", to: "brunks#new_comment_brunk", as: "new_comment_brunk"

end

app/models/brunk.rb
# == Schema Information
#
# Table name: brunks
#
#  id               :integer          not null, primary key
#  runner_one       :integer
#  runner_two       :integer
#  property_one     :integer
#  property_two     :integer
#  difference_value :integer
#  offer_one        :integer
#  offer_two        :integer
#  state_one        :integer
#  state_two        :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  runner_one_id    :integer
#  runner_two_id    :integer
#  property_one_id  :integer
#  property_two_id  :integer
#

class Brunk < ApplicationRecord
	 belongs_to :runner_one, :class_name => 'Runner'
	 belongs_to :runner_two, :class_name => 'Runner'
	 belongs_to :property_one, :class_name => 'Property'
	 belongs_to :property_two, :class_name => 'Property'
end

app/controllers/brunks_controller.rb
class BrunksController < ApplicationController
before_action :authenticate_runner!
layout 'runner_home'

  def step1
    @property = Property.find(params[:id])
    @properties = Property.where(brunk: true).where.not(runner_id: current_runner.id).paginate(:page => params[:page], :per_page => 20)
  end

  def step2
     @property = Property.find(params[:id1])
     @property1 = Property.find(params[:id2])
     cookies[:property]   = @property.id 
     cookies[:property1] = @property1.id

  end

  def my_brunks

    @brunks = current_runner.brunks

  end

  def show
    @brunk = Brunk.find(params[:id])
    @brunk_tracing = BrunkTracing.all
  end

  def show_required
    @brunk = Brunk.find(params[:id])
  end


  def brunks_required

     @brunks = current_runner.brunks_one

  end


  def create_brunk
     
     Brunk.create(runner_one_id: params[:idrunnerone], runner_two_id: params[:idrunnertwo], property_one_id: params[:idprone], property_two_id: params[:idprtwo])

  end


 def new_comment_brunk
     
  @brunk_tracing = BrunkTracing.create(brunk_id: params[:brunk_id], comment: params[:comment], offer: params[:offer], runner_id: params[:runner_id])
  
  end


end



  

app/helpers/brunks_helper.rb
module BrunksHelper
end

app/views/brunks/_brunk1.html.erb
<% @property = Property.find(@brunk.property_one_id)%>
   <% @property1 = Property.find(@brunk.property_two_id)%>





<div class="row" style="background: #fff; border-radius: 4px;">
 <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="col-md-6">
      <div class="row mb-3">
         <div class="col-md-10 col-md-offset-1">
         
            <h3 align="center">Mi propiedad para el Brunk</h3><br>
         
             <%=render 'property_card' , property: @property %>
      
              </div>
          
      </div>
    </div>
 <div class="col-md-6">
      <div class="row mb-3">
         <div class="col-md-10 col-md-offset-1">
         
            <h3 align="center">Propiedad Solicitada</h3><br>
         
             <%=render 'property_card' , property: @property1  %>
              
   
              </div>
          
      </div>
    </div>

    <div class="col-md-6 col-md-offset-3">
         <%if (@property1.prince - @property.prince) > 0 %>
                              <div class="alert alert-danger">
                                   <small><b>Debes dar</b></small>
                                    <small><%= number_to_currency((@property1.prince - @property.prince ), precision: 0) %></small>
                                    
                              </div>    
                               
                                  
                                  
                                  <%else%>
                        <div class="alert alert-success">
                                      <small><b>Te deben dar</b></small>
                                    <small><%= number_to_currency(( @property.prince - @property1.prince), precision: 0) %></small> 
                           </div> 
        <%end%>


    
 </div>  




</div>

</div>

app/views/brunks/_brunk2.html.erb
<% @property = Property.find(@brunk.property_one_id)%>
   <% @property1 = Property.find(@brunk.property_two_id)%>


<link href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css" rel="stylesheet" media="screen">  


 <div class="row user-menu-container square">
        <div class="col-md-10 col-md-offset-1 user-details">
            <div class="row coralbg white">
                <div class="col-md-9 no-pad">
                    <div class="user-pad">
                        <h3>El Runner <%=@brunk.runner_one.name%></h3>
                        <h4 class="white"><i class="fa fa-check-circle-o"></i>Quiere hacer un brunk</h4>
                       
                       
                    </div>
                </div>
                <div class="col-md-3 no-pad">
                    <div class="user-image">
                        <img src="https://farm7.staticflickr.com/6163/6195546981_200e87ddaf_b.jpg" class="img-responsive thumbnail">
                    </div>
                </div>
            </div>
            <div class="row overview">
                <div class="col-md-4 user-pad text-center">
                    <h3>SEGUIDORES</h3>
                    <h4>2,784</h4>
                </div>
                <div class="col-md-4 user-pad text-center">
                    <h3>PROPIEDADES</h3>
                    <h4>456</h4>
                </div>
                <div class="col-md-4 user-pad text-center">
                    <h3>CALIFICACION</h3>
                    <h4>10</h4>
                </div>
            </div>
        </div>
        
      
    </div>






<div class="row" style="background: #fff; border-radius: 4px;">
 <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="col-md-6">
      <div class="row mb-3">
         <div class="col-md-10 col-md-offset-1">
         
            <h3 align="center">Propiedad que te Ofrece</h3><br>
         
             <%=render 'property_card' , property: @property %>
            
   
              </div>
          
      </div>
    </div>
 <div class="col-md-6">
      <div class="row mb-3">
         <div class="col-md-10 col-md-offset-1">
         
            <h3 align="center">Propiedad que Quiere</h3><br>
         
             <%=render 'property_card' , property: @property1  %>
           
              </div>
          
      </div>
    </div>
<div class="col-md-6 col-md-offset-3">
         <%if (@property.prince - @property1.prince) > 0 %>
                    
                              <div class="alert alert-danger">
                                   <small><b>Debes dar</b></small>
                                    <small><%= number_to_currency((@property.prince - @property1.prince ), precision: 0) %></small>
                                    
                              </div>    
                               
                                  
                                  
                                  <%else%>
                        <div class="alert alert-success">
                                      <small><b>Te deben dar</b></small>
                                    <small><%= number_to_currency(( @property1.prince - @property.prince), precision: 0) %></small> 
                           </div> 
        <%end%>


    
 </div>  


</div>

</div>



<style >
  .square, .btn {
    border-radius: 0px!important;
}

/* -- color classes -- */
.coralbg {
    background-color: #31abda;;
} 

.coral {
    color: #FA396f;
}

.turqbg {
    background-color: #46D8D2;
}

.turq {
    color: #46D8D2;
}

.white {
    color: #fff!important;
}

/* -- The "User's Menu Container" specific elements. Custom container for the snippet -- */
div.user-menu-container {
  z-index: 10;
  background-color: #fff;
  margin-top: 20px;
  background-clip: padding-box;
  opacity: 0.97;
  filter: alpha(opacity=97);
  -webkit-box-shadow: 0 1px 6px rgba(0, 0, 0, 0.175);
  box-shadow: 0 1px 6px rgba(0, 0, 0, 0.175);
}

div.user-menu-container .btn-lg {
    padding: 0px 12px;
}

div.user-menu-container h4 {
    font-weight: 300;
    color: #8b8b8b;
}

div.user-menu-container a, div.user-menu-container .btn  {
    transition: 1s ease;
}

div.user-menu-container .thumbnail {
    width: 77%;
    min-height: 127px;
   border: 0px!important;
   padding: 0px;
   border-radius: 0;
   border: 0px!important;
}

/* -- Vertical Button Group -- */
div.user-menu-container .btn-group-vertical {
    display: block;
}

div.user-menu-container .btn-group-vertical>a {
    padding: 20px 25px;
    background-color: #46D8D2;
    color: white;
    border-color: #fff;
}

div.btn-group-vertical>a:hover {
    color: white;
    border-color: white;
}

div.btn-group-vertical>a.active {
    background: #FA396F;
    box-shadow: none;
    color: white;
}
/* -- Individual button styles of vertical btn group -- */
div.user-menu-btns {
    padding-right: 0;
    padding-left: 0;
    padding-bottom: 0;
}

div.user-menu-btns div.btn-group-vertical>a.active:after{
  content: '';
  position: absolute;
  left: 100%;
  top: 50%;
  margin-top: -13px;
  border-left: 0;
  border-bottom: 13px solid transparent;
  border-top: 13px solid transparent;
  border-left: 10px solid #46D8D2;
}
/* -- The main tab & content styling of the vertical buttons info-- */
div.user-menu-content {
    color: #323232;
}

ul.user-menu-list {
    list-style: none;
    margin-top: 20px;
    margin-bottom: 0;
    padding: 10px;
    border: 1px solid #eee;
}
ul.user-menu-list>li {
    padding-bottom: 8px;
    text-align: center;
}

div.user-menu div.user-menu-content:not(.active){
  display: none;
}

/* -- The btn stylings for the btn icons -- */
.btn-label {position: relative;left: -12px;display: inline-block;padding: 6px 12px;background: rgba(0,0,0,0.15);border-radius: 3px 0 0 3px;}
.btn-labeled {padding-top: 0;padding-bottom: 0;}

/* -- Custom classes for the snippet, won't effect any existing bootstrap classes of your site, but can be reused. -- */

.user-pad {
    padding: 20px 25px;
}

.no-pad {
    padding-right: 0;
    padding-left: 0;
    padding-bottom: 0;
}

.user-details {
    background: #eee;
   
}

.user-image {
  max-height:127px;
  overflow:hidden;
}

.overview h3 {
    font-weight: 300;
    margin-top: 14px;
    margin: 10px 0 0 0;
    font-size: 16px;
}

.overview h4 {
    font-weight: bold!important;
    font-size:20px;
    margin-top: 0;
}

.view {
    position:relative;
    overflow:hidden;
    margin-top: 10px;
}

.view p {
    margin-top: 20px;
    margin-bottom: 0;
}
 
.caption {
    position:absolute;
    top:0;
    right:0;
    background: rgba(70, 216, 210, 0.44);
    width:100%;
    height:100%;
    padding:2%;
    display: none;
    text-align:center;
    color:#fff !important;
    z-index:2;
}

.caption a {
    padding-right: 10px;
    color: #fff;
}

.info {
    display: block;
    padding: 10px;
    background: #eee;
    text-transform: uppercase;
    font-weight: 300;
    text-align: right;
}

.info p, .stats p {
    margin-bottom: 0;
}

.stats {
    display: block;
    padding: 10px;
    color: white;
}

.share-links {
    border: 1px solid #eee;
    padding: 15px;
    margin-top: 15px;
}

.square, .btn {
    border-radius: 0px!important;
}

/* -- media query for user profile image -- */
@media (max-width: 767px) {
    .user-image {
        max-height: 400px;
    }
}
</style>


<script>
  
  $(document).ready(function() {
    var $btnSets = $('#responsive'),
    $btnLinks = $btnSets.find('a');
 
    $btnLinks.click(function(e) {
        e.preventDefault();
        $(this).siblings('a.active').removeClass("active");
        $(this).addClass("active");
        var index = $(this).index();
        $("div.user-menu>div.user-menu-content").removeClass("active");
        $("div.user-menu>div.user-menu-content").eq(index).addClass("active");
    });
});

$( document ).ready(function() {
    $("[rel='tooltip']").tooltip();    
 
    $('.view').hover(
        function(){
            $(this).find('.caption').slideDown(250); //.fadeIn(250)
        },
        function(){
            $(this).find('.caption').slideUp(250); //.fadeOut(205)
        }
    ); 
});
</script>

app/views/brunks/_property.html.erb
 <div class="card">
                    <div class="card-body">
                        <div class="row" style="padding: 9px;">

                            <div class="col-md-3" style="padding-bottom:20px;">
                                
                                <%= property.images? ? image_tag(property.images_url(:medium)) : image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiS5HhpjhUIciPRhbw4Qe_9ms0umoNaHNRltq8qZD13yyRDY6wyQ") %>
                            </div>

                            <div class="col-md-9 info" style="">
                                <p style="margin-left: 5px;margin-bottom: 10px;" > <strong><%= property.property_type%> - <%= property.city%> - <%=property.country.name if property.country %></strong>
                            
                                </p>
                               <small > <strong> Area: </strong><%= property.area%>,00 m2</small>
                              <small><strong> Hab: </strong><%= property.number_bedrooms%> hab</small>
                              <small><strong> Estrato: </strong> <%= property.stratum%></small>
                            </div>

                            

                              <div class="col-md-12">
                                <div class="row" style="padding-left: 10px;">
                                  
                              <div class="col-md-4" style="padding-left: 0px">
                                   <%= link_to 'Ver Propiedad ', property, class: "btn2", style: "float:right"%>
                            </div>
                                   <div class="col-md-8" style="    padding-right: 27px; font-size: 25px;text-align: left;">
                                    <small><b>Precio</b></small>:
                                    <small><%= number_to_currency(property.prince, precision: 0) %></small>
                                  </div>
                                  
                    </div>
               </div>
          </div>                            
     </div>
</div>

app/views/brunks/_property_cambio.html.erb
                  <div class="card">
                    <div class="card-body">
                        <div class="row" style="padding: 9px;">

                          <div class="col-md-3 propertyc-img" style="padding-bottom:20px;">
                                
                                <%= property.images? ? image_tag(property.images_url(:medium)) : image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiS5HhpjhUIciPRhbw4Qe_9ms0umoNaHNRltq8qZD13yyRDY6wyQ") %>
                            </div>

                            
                            <div class="col-md-9 info" style="">

                               <div class="col-md-12">
                                <p style="margin-left: 5px;margin-bottom: 10px;" > <strong><%= property.property_type%> - <%= property.city%> - <%=property.country.name if property.country%></strong>
                              
                                </p>
                                <small > <strong> Area: </strong><%= property.area%>,00 m2</small>
                              <small><strong> Habitaciones: </strong><%= property.number_bedrooms%> hab</small>
                              <small><strong> Estrato: </strong> <%= property.stratum%></small>
                              </div>
                           
                              </div>
                            

                              <div class="col-md-12">
                                <div class="row" style="padding-left: 10px;">
                                  
                              <div class="col-md-4" style="padding-left: 0px">
                               <p> <%= link_to 'Ver Propiedad', property, class: "btn2"%></p>
                               <p>  <%= link_to 'Brunk', step2_path(property1.id, property.id), class: "btn2" %></p>
                                </div>

                                  <div class="col-md-8" style="margin-top: 5px;">
                                    <div class="col-md-6" style="    padding-right: 27px; font-size: 16px;">
                                     <small><b>Precio</b></small>
                                    <small><%= number_to_currency(property.prince, precision: 0) %></small>
                                  </div>


                                   <%if (property.prince - property1.prince) > 0 %>
                                  <div class="col-md-6 text-right" style="    padding-right: 18px;float: right; font-size: 16px;color: red;">
                                 
                                
                                   <small><b>Debes dar</b></small>
                                    <small><%= number_to_currency((property.prince - property1.prince ), precision: 0) %></small>
                                     </div>
                                  <%else%>
                                  <div class="col-md-6 text-right" style="    padding-right: 20px;font-size: 18px;color: green;">
                                      <small><b>Te deben dar</b></small><br>
                                    <small><%= number_to_currency(( property1.prince - property.prince), precision: 0) %></small>
                                     </div>
                                  <%end%>
                               </div>  
                                   
                                    
                                 
                                  
                           
                          </div>
                        </div>                            
                      
                    </div>
                  </div>  
                 </div>    
<style>
hr
{
    margin-top: 5px;
    margin-bottom: 5px;
}
.alert-success, .alert-danger
{
  font-size: 20px;
  padding: 5px;
  text-align: center;
}
  .propertyc-img img{
    width: 120px !important;
    height: 80px; 

  }
  .info small
  {
   
    padding: 4px;
    margin-right: 10px;
  }
 .card
 {
  margin-bottom: 10px !important;
 } 
</style>                    

app/views/brunks/_property_card.html.erb
 <div class="card" style="margin-bottom: 5px !important;">
                    <div class="card-body">
                        <div class="row" style="padding: 9px;">

                            <div class="col-md-12 text-center property-img" style="padding-bottom:20px;">
                                
                                <%= property.images? ? image_tag(property.images_url(:medium)) : image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiS5HhpjhUIciPRhbw4Qe_9ms0umoNaHNRltq8qZD13yyRDY6wyQ") %>

                            </div>

                            <div class="col-md-12 info1" style="">

                               <div class="col-md-12 text-center">
                                <p style="margin-left: 5px;margin-bottom: 10px;" > <strong><%= property.property_type%> - <%= property.city%> - <%=property.country.name if property.country%></strong>
                               
                                </p>
                                <small > <strong> Area: </strong><%= property.area%>,00 m2</small>
                              <small><strong> Habitaciones: </strong><%= property.number_bedrooms%> hab</small><br>
                              <small><strong> Estrato: </strong> <%= property.stratum%></small>
                              </div>
                            

                          

                              <div class="col-md-12">
                                <hr>
                                    <div class="row" style="padding-left: 10px;">
                                      
                                 
                                       <div class="col-md-12" style="    padding-right: 27px; font-size: 20px;text-align: center;">
                                   
                                        <small><b>Precio: </b><%= number_to_currency(property.prince, precision: 0) %></small>
                                      </div>
                                  
                            </div>
                         </div>
                         <div class="col-md-12" style="padding-left: 0px;margin-top: 20px">
                                <%= link_to 'Ver Propiedad', @property1, class: "btn2" %>
                            </div>
                   </div>
          </div>                            
     </div>
</div>

<style>
hr
{
    margin-top: 5px;
    margin-bottom: 5px;
}
.alert-success, .alert-danger
{
  font-size: 20px;
  padding: 5px;
  text-align: center;
}
  .property-img img{
    width: 200px !important;
    height: 130px; 

  }
  .info1 small
  {
   
    padding: 4px;
    margin-right: 10px;
  }

</style>

app/views/brunks/_show_items.html.erb
 <div class="card" style="padding-top: 5px;">
    <div class="card-body">

      <div class="image-profile">
        <%= brunk_tracing.runner.image? ? image_tag(brunk_tracing.runner.image_url(:logo)) : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg", style: "height: 104px;")%>
      </div>

        <div class="col-md-2" style="float: right;">
          <b>Oferto</b><br>
          <%= brunk_tracing.offer%>
        </div>
      

        <div class="col-md-8">
          <b>Email</b><br>
          <%= brunk_tracing.runner.email%>
        </div>

        <div class="row">

          <div class="col-md-8" style="padding: 10px 10px 10px 16px;">
            <b>Mensajes</b><br>
            <%= brunk_tracing.comment%>
          </div>

        </div>

    </div>
</div>

<style>

  .image-profile img{
    border-radius: 50%;
  }

  .image-profile{
    margin-top: 10px;
    float: left; 
    margin-left: 10px
  }

</style>

app/views/brunks/brunks_required.html.erb
   <% @brunks.each do |brunk| %>
   <% @property = Property.find(brunk.property_one_id)%>
   <% @property1 = Property.find(brunk.property_two_id)%>

<div class="row" style="background: #fff; border-radius: 4px;">
   <p style="text-align: right;"> <%=link_to "Gestion Cambio" ,show_path(brunk.id), class: "btn btn-primary" %></p>
 
 <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

    <div class="col-md-6">
      <div class="row mb-3">
         <div class="col-md-12">
         
            <h3 align="center">Propiedad que te Ofrecen</h3><br>
         
                 <%=render 'property' , property: @property  %>
               
   
              </div>
          
      </div>
    </div>
     <div class="col-md-6">
      <div class="row mb-3">
         <div class="col-md-12">
         
            <h3 align="center">Propiedad que Quieren</h3><br>
         
             <%=render 'property' , property: @property1  %>
               
   
              </div>
          
      </div>
    </div>
  <div class="col-md-6 col-md-offset-3">
         <%if (@property.prince - @property1.prince) > 0 %>
                    
                              <div class="alert alert-danger">
                                   <small><b>Debes dar</b></small>
                                    <small><%= number_to_currency((@property.prince - @property1.prince ), precision: 0) %></small> <%=link_to "Ver Detalles" ,show_path(brunk.id), class: "btn btn-danger" , style: "margin-left:30px;" %>

                              </div>    
                               
                                  
                                  
                                  <%else%>
                        <div class="alert alert-success">
                                      <small><b>Te deben dar</b></small>
                                    <small><%= number_to_currency(( @property1.prince - @property.prince), precision: 0) %></small> <%=link_to "Ver Detalles" ,show_path(brunk.id), class: "btn btn-success" , style: "margin-left:30px;"%>
                           </div> 
                           <br>
        <%end%>


    
 </div>  
</div>

</div>




<%end%>


<style>
.alert-success, .alert-danger
{
  font-size: 20px;
  padding: 5px;
  text-align: center;
}
  img{
    width: 100px !important;
    height: 60px; 

  }
  .info small
  {
       
    padding: 4px;
    margin-right: 10px;
  }
 .card
 {
  margin-bottom: 0px !important;
 } 
</style>

app/views/brunks/my_brunks.html.erb
   <% @brunks.each do |brunk| %>
   <% @property = Property.find(brunk.property_one_id)%>
   <% @property1 = Property.find(brunk.property_two_id)%>

<div class="row" style="background: #fff; border-radius: 4px;">
   <p style="text-align: right;"> </p>
 
 <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

    <div class="col-md-6">
      <div class="row mb-3">
         <div class="col-md-12">
         
            <h3 align="center">Propiedad que Ofreces</h3><br>
         
               <%=render 'property' , property: @property  %>
               
   
              </div>
          
      </div>
    </div>
     <div class="col-md-6">
      <div class="row mb-3">
         <div class="col-md-12">
         
            <h3 align="center">Propiedad que Quieres</h3><br>
         
             <%=render 'property' , property: @property1  %>
               
   
            </div>
          
      </div>
    </div>
  <div class="col-md-6 col-md-offset-3">
         <%if (@property1.prince - @property.prince) > 0 %>
                    
                              <div class="alert alert-danger">
                                   <small><b>Debes dar</b></small>
                                    <small><%= number_to_currency((@property1.prince - @property.prince ), precision: 0) %></small>
                                    <%=link_to "Ver Detalles" ,show_path(brunk.id), class: "btn btn-danger" , style: "margin-left:30px;" %>
                              </div>    
                               
                                  
                                  
                                  <%else%>
                        <div class="alert alert-success">
                                      <small><b>Te deben dar</b></small>
                                    <small><%= number_to_currency(( @property.prince - @property1.prince), precision: 0) %></small> <%=link_to "Ver Detalles" ,show_path(brunk.id), class: "btn btn-success" , style: "margin-left:30px;"%>
                           </div> 
        <%end%>


    
 </div>  
</div>

</div>
<br>
<%end%>


<style>
.alert-success, .alert-danger
{
  font-size: 20px;
  padding: 5px;
  text-align: center;
}
  img{
    width: 100px !important;
    height: 60px;	

  }
  .info small
  {
   
    padding: 4px;
    margin-right: 10px;
  }
 .card
 {
  margin-bottom: 0px !important;
 } 
</style>

app/views/brunks/new_comment_brunk.js.erb
$('.comentarios').prepend('<%= j render "show_items", brunk_tracing: @brunk_tracing %>');

app/views/brunks/show.html.erb
<% @property = Property.find(@brunk.property_one_id)%>
   <% @property1 = Property.find(@brunk.property_two_id)%>

<% if current_runner.id == @brunk.runner_one.id %>
  <%= render 'brunk1'%>
<%else%>
   <%= render 'brunk2'%>
<%end%>

<div class="row">
    <div class="col-md-12 form-send">
        <div class="w3-container" style="padding: 0px; ">
   

         <%= form_tag new_comment_brunk_path, remote: true, class: "form-inline"  %>
         	 <div class="form-group col-md-6">		
	            <label style="">Comentario</label><br>
	            <%= text_field_tag :comment ,nil, class: "form form-control", style: "width:100%"%>
            </div>

            <div class="form-group col-md-3">		
            <label style="">Oferta</label><br>
             <%= text_field_tag :offer ,nil, class: "form form-control", :value => "$"%>
            </div>

           <%=hidden_field_tag :brunk_id, @brunk.id%>
           <%=hidden_field_tag :runner_id, current_runner.id%>


           	<div class="form-group col-md-3">	<br>	
              <input type="submit" class="btn btn-primary btn-block">
            </div>	
        </div>
    </div>
</div>

<div class="comentarios"> 
  <% @brunk_tracing.each do |brunk_tracing| %>
    <%= render "show_items", brunk_tracing: brunk_tracing %>
  <% end -%>
</div>

app/views/brunks/show_required.html.erb
<% @property = Property.find(@brunk.property_one_id)%>
   <% @property1 = Property.find(@brunk.property_two_id)%>

<div class="row" style="background: #fff; border-radius: 4px;">
 <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="col-md-6">
      <div class="row mb-3">
         <div class="col-md-10 col-md-offset-1">
         
            <h3 align="center">Propiedad que te Ofrecen</h3><br>
         
             <%=render 'property_card' , property: @property %>
                  <br>
   
              </div>
          
      </div>
    </div>
 <div class="col-md-6">
      <div class="row mb-3">
         <div class="col-md-10 col-md-offset-1">
         
            <h3 align="center">Propiedad que Quieren</h3><br>
         
             <%=render 'property_card' , property: @property1  %>
                  <br>
   
              </div>
          
      </div>
    </div>



</div>

</div>

app/views/brunks/update.js.erb
$('#product-modal').modal('hide');
$('#id<%=@post.id%>').html("<%= j render 'show_items'");