config/routes.rb
Rails.application.routes.draw do
  




  get 'contacts/index'
  get 'contacts/create'
  #brunk routes
  get 'brunks/step1/:id' , to: 'brunks#step1', as: 'step1'
  get 'brunks/step2/:id1/:id2' , to: 'brunks#step2', as: 'step2'
  get 'brunks/my_brunks', to: 'brunks#my_brunks', as: 'my_brunks'
  get 'brunks/show/:id', to: 'brunks#show', as: 'show'
  get 'brunks/show_required/:id', to: 'brunks#show_required', as: 'show_required'
  get 'brunks/brunks_required', to: 'brunks#brunks_required', as: 'brunks_required'

  post 'brunks/create_brunk', to: 'brunks#create_brunk', as: 'create_brunk'

  #
  resources :properties
  resources :countries
  devise_for :runners , :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  
  get "runner_home", to: "welcome#runner_home", as: "runner_home"
  
  get "pagina_show", to: "welcome#pagina_show", as: "pagina_show"
  
  get "runners_avatar", to: "welcome#runners_avatar", as: "runners_avatar"

  get "index_contacs", to: "welcome#index_contacs", as: "index_contacs"

  post "cambios/:id", to: "properties#cambios", as: "cambios"

  #contacto routes

  post "new_contact", to: "contacts#create", as: "new_contact"
  get 'properties/:id' , to: 'properties#show', as: 'properties_show'

  
  get 'crear_call/:id' , to: 'contacts#crear_call', as: 'crear_call'  
  post "new_comment_brunk", to: "brunks#new_comment_brunk", as: "new_comment_brunk"

end

app/views/layouts/runners.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ebrunk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <!---------------------------- BOOSTRAMP ---------------------------------->
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
     
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!---------------------------- BOOSTRAMP ---------------------------------->


    <!---------------------------- w3schools ---------------------------------->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!---------------------------- w3schools ---------------------------------->


    <!---------------------------- carousel ---------------------------------->


    <%= stylesheet_link_tag    'https://unpkg.com/flickity@2/dist/flickity.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://code.jquery.com/jquery-1.11.3.min.js', 'data-turbolinks-track': 'reload' %>
    
    <!---------------------------- carousel ---------------------------------->

    
  </head>
<!--
  <div class="navbar-wrapper">
    <div class="container-fluid">
        <nav class="navbar navbar-fixed-top">
            <div class="container" style="margin-right: 0px !important;">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#" style="position: relative; left: -57px;">Logo</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><%= link_to "Home", root_path %></li>
                        <li><%= link_to "Publicaciones",properties_path  %></li>
                    <% if runner_signed_in? %>
                        <li><%= link_to "Crear Nueva Propiedad", properties_path  %></li>
                    <% end -%>
                    </ul> 


                    <ul class="nav navbar-nav pull-right">
                      <% if runner_signed_in? %>
                        <li class=" dropdown"><a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cuenta<span class="caret"></span></a>
                            <ul class="dropdown-menu" style="    min-width: 111px;">
                                <li> <%= link_to 'Editar Perfil', edit_runner_registration_path, :class => 'navbar-link' %></li>
                                <li><%= link_to "Salir", destroy_runner_session_path, method: :delete, :class => 'navbar-link'  %></li>
                            </ul>
                            <% else %>
                        <li class=" dropdown"><a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Registrate<span class="caret"></span></a>
                            <ul class="dropdown-menu" style="    min-width: 111px;">
                                <li> <%= link_to "Registrate", new_runner_registration_path, :class => 'navbar-link'  %></li>
                                <li><%= link_to "Ingresar", new_runner_session_path, :class => 'navbar-link'  %></li>
                            </ul>
                          <% end -%>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>
-->

  <a><img src="https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/59/WhatsApp_Image_2018-10-25_at_1.53.16_PM.jpeg" style="border-radius: 50%; width: 180px !important; margin-bottom: 10px; margin-top: 10px; height: 80px !important;position: absolute;
     z-index: 10;"></a>


<div id='cssmenu'>
<ul>

   <li><%= link_to "Home", root_path %></li>
   <li><%= link_to "Propiedades", properties_path %></li>
   <li><%= link_to "Runners", runners_avatar_path %></li>
   <% if runner_signed_in? %>

    <li class='has-sub' style="float: right; margin-right: 100px;  cursor: pointer;"><a><span><%= current_runner.name%></span></a>
      <ul  style="max-width: 80px; ">
        <li><%= link_to "Home", runner_home_path %></li>
        <li><%= link_to 'Editar', edit_runner_registration_path, :class => 'navbar-link' %></li>
        <li class='last'><%= link_to "Salir", destroy_runner_session_path, method: :delete, :class => 'navbar-link'  %></li>
      </ul>
    </li>

   <% else %>


    <li class='has-sub' style="float: right; margin-right: 100px;"><a href='#'><span>Ingresar</span></a>
      <ul>
        <li><%= link_to "Registrate", new_runner_registration_path, :class => 'navbar-link'  %></li>
        <li class='last'><%= link_to "Ingresar", new_runner_session_path, :class => 'navbar-link'  %></li>
      </ul>
    </li>

   <% end -%>

</ul>
</div>
<br>

  <body>
    <%= yield %>
  </body>
</html>